### ISSUE TITLE
Error with midi file

### ISSUE THREAD

**Issue by davidecampello** [IraKorshunova/GenMeowth#1]
Hi, I would like to try your application. I created a simple midi file with finale but I have an error loading it. Can you help me?
This is the midi file:
https://drive.google.com/file/d/16SHWqC0vM-6DSz3YDGhtZKcsuJa_Yzlb/view?usp=sharing

Thanks
Davide

**Comment by IraKorshunova** [comment]
Hi,
I'm very sorry, but this is such an old code that I have no idea what it's supposed to do when loading midi files.
